name: coverity

on:
  push:
    branches: 'coverity'
  pull_request:
    branches: 'master'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install git build-essential autoconf libtool libpcap-dev pkg-config libxml2-dev
        ( git clone --depth 1 https://github.com/CESNET/nemea-framework /tmp/nemea-framework; cd /tmp/nemea-framework; ./bootstrap.sh &&./configure --bindir=/usr/bin/nemea/ -q &&make -j10 && sudo make install; sudo ldconfig)
        ( git clone --depth 1 https://github.com/CESNET/nemea-modules /tmp/nemea-modules; cd /tmp/nemea-modules; ./bootstrap.sh &&./configure --bindir=/usr/bin/nemea/ -q &&make -j10 && sudo make install; )
    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure --with-nemea
    - uses: vapier/coverity-scan-action@v1
      with:
        email: cejkat@cesnet.cz
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
